spring.application.name=gestion

# Base de datos local
spring.datasource.url=jdbc:mysql://localhost:3306/rrhh_db
spring.datasource.username=root
spring.datasource.password=admin

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Formato fechas
spring.jackson.time-zone=America/Bogota
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# Manejo de errores
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Inteligencia Artificial
spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

# Ruta de Python (Usa ./venv/... para Windows por defecto)
PYTHON_EXE_PATH=./venv/Scripts/python.exe
